# Generated by Django 5.0.3 on 2024-04-02 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime(2024, 4, 2, 12, 47, 12, 413195, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
